<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Application/Please.Application/Please.Application.csproj"/>
    <ProjectReference Include="../../../src/Domain/Please.Domain/Please.Domain.csproj"/>
    <ProjectReference Include="../../TestUtilities/Please.TestUtilities/Please.TestUtilities.csproj"/>
    <ProjectReference Include="../../../src/Presentation/Please.Console/Please.Console.csproj"/>
  </ItemGroup>
</Project>
