using Microsoft.Extensions.Logging;
using NSubstitute;
using Please.Domain.Services;
using Please.Infrastructure.Services;
using Please.TestUtilities.Builders;
using Please.Domain.Enums;
using Shouldly;

namespace Please.Infrastructure.UnitTests.Services;

public class FileServiceTests : IDisposable
{
    private readonly string _testDirectory;
    private readonly FileService _fileService;
    private readonly IPlatformService _platformService;

    public FileServiceTests()
    {
        // Create a unique directory for each test instance
        _testDirectory = Path.Combine(Path.GetTempPath(), "PleaseFileServiceTests", Guid.NewGuid().ToString());
        Directory.CreateDirectory(_testDirectory);

        var logger = Substitute.For<ILogger<FileService>>();
        _platformService = Substitute.For<IPlatformService>();
        _platformService.GetDataDirectory().Returns(_testDirectory);
        
        _fileService = new FileService(logger, _platformService);
    }

    public void Dispose()
    {
        // Clean up test directory after each test
        if (Directory.Exists(_testDirectory))
        {
            Directory.Delete(_testDirectory, true);
        }
    }

    [Fact]
    public async Task SaveScriptToFileAsync_with_valid_script_saves_successfully()
    {
        // Arrange
        var script = ScriptResponseBuilder.Create()
            .WithScript("Write-Host 'Hello World'")
            .WithTask("say hello")
            .WithScriptType(ScriptType.PowerShell)
            .Build();

        // Act
        var result = await _fileService.SaveScriptToFileAsync(script, _testDirectory);

        // Assert
        result.IsSuccess.ShouldBeTrue();
        result.Value.ShouldNotBeNull();
        File.Exists(result.Value!).ShouldBeTrue();
        
        var content = await File.ReadAllTextAsync(result.Value!);
        content.ShouldContain("Write-Host 'Hello World'");
        content.ShouldContain("# Generated by Please v6.0.0");
        content.ShouldContain("# Task: say hello");
    }

    [Fact]
    public async Task SaveScriptToFileAsync_with_null_script_returns_failure()
    {
        // Act
        var result = await _fileService.SaveScriptToFileAsync(null!);

        // Assert
        result.IsFailure.ShouldBeTrue();
        result.Error.ShouldBe("Script cannot be null");
    }

    [Fact]
    public async Task SaveScriptToFileAsync_with_empty_script_returns_failure()
    {
        // Arrange
        var script = ScriptResponseBuilder.Create()
            .WithScript("")
            .Build();

        // Act
        var result = await _fileService.SaveScriptToFileAsync(script);

        // Assert
        result.IsFailure.ShouldBeTrue();
        result.Error.ShouldBe("Script content cannot be empty");
    }

    [Fact]
    public async Task SaveScriptToFileAsync_handles_file_name_conflicts()
    {
        // Arrange
        var script = ScriptResponseBuilder.Create()
            .WithScript("echo 'test'")
            .WithTask("test script")
            .WithScriptType(ScriptType.Bash)
            .Build();

        // Act - Save the same script twice
        var result1 = await _fileService.SaveScriptToFileAsync(script, _testDirectory);
        var result2 = await _fileService.SaveScriptToFileAsync(script, _testDirectory);

        // Assert
        result1.IsSuccess.ShouldBeTrue();
        result2.IsSuccess.ShouldBeTrue();
        result1.Value.ShouldNotBe(result2.Value); // Different file paths
        
        File.Exists(result1.Value!).ShouldBeTrue();
        File.Exists(result2.Value!).ShouldBeTrue();
        
        // Second file should have a counter
        Path.GetFileName(result2.Value!).ShouldContain("_1");
    }

    [Theory]
    [InlineData(ScriptType.PowerShell, ".ps1")]
    [InlineData(ScriptType.Bash, ".sh")]
    [InlineData(ScriptType.Python, ".py")]
    [InlineData(ScriptType.Command, ".bat")] // On Windows
    public void GetFileExtension_returns_correct_extension(ScriptType scriptType, string expectedExtension)
    {
        // Act
        var extension = _fileService.GetFileExtension(scriptType);

        // Assert - On Linux, Command scripts get .sh instead of .bat, so we need to handle that
        if (scriptType == ScriptType.Command && !OperatingSystem.IsWindows())
        {
            extension.ShouldBe(".sh");
        }
        else
        {
            extension.ShouldBe(expectedExtension);
        }
    }

    [Theory]
    [InlineData("create a script to list files", "list_files")]
    [InlineData("generate backup script", "generate_backup_script")]
    [InlineData("script with special chars @#$%", "script_with_special_chars")]
    [InlineData("", "please_script_")]
    [InlineData("   ", "please_script_")]
    public void GenerateFileName_creates_safe_file_names(string taskDescription, string expectedStart)
    {
        // Act
        var fileName = _fileService.GenerateFileName(taskDescription);

        // Assert
        fileName.ShouldNotBeNull();
        if (expectedStart == "please_script_")
        {
            fileName.ShouldStartWith(expectedStart);
        }
        else
        {
            fileName.ShouldBe(expectedStart);
        }
        
        // Should not contain invalid file name characters
        var invalidChars = Path.GetInvalidFileNameChars();
        foreach (var invalidChar in invalidChars)
        {
            fileName.ShouldNotContain(invalidChar.ToString());
        }
    }

    [Fact]
    public void GetDefaultSaveDirectory_returns_valid_directory()
    {
        // Act
        var directory = _fileService.GetDefaultSaveDirectory();

        // Assert
        directory.ShouldNotBeNullOrEmpty();
        // Should not throw when trying to create the directory
        Should.NotThrow(() => Directory.CreateDirectory(directory));
    }

    [Fact]
    public async Task SaveScriptToFileAsync_includes_metadata_in_file_content()
    {
        // Arrange
        var script = ScriptResponseBuilder.Create()
            .WithScript("Get-Process")
            .WithTask("list running processes")
            .WithScriptType(ScriptType.PowerShell)
            .WithProvider(ProviderType.OpenAi)
            .WithModel("gpt-4")
            .WithRiskLevel(RiskLevel.Low)
            .Build();

        // Act
        var result = await _fileService.SaveScriptToFileAsync(script, _testDirectory);

        // Assert
        result.IsSuccess.ShouldBeTrue();
        var content = await File.ReadAllTextAsync(result.Value!);
        
        content.ShouldContain("# Generated by Please v6.0.0");
        content.ShouldContain("# Task: list running processes");
        content.ShouldContain("# Provider: OpenAi (gpt-4)");
        content.ShouldContain("# Risk Level: Low");
        content.ShouldContain("Get-Process");
    }
}