<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio"/>
    <PackageReference Include="coverlet.collector"/>
    <PackageReference Include="NSubstitute"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Infrastructure\Please.Infrastructure\Please.Infrastructure.csproj"/>
    <ProjectReference Include="..\..\..\src\Domain\Please.Domain\Please.Domain.csproj"/>
    <ProjectReference Include="..\..\..\src\Application\Please.Application\Please.Application.csproj"/>
    <ProjectReference Include="..\..\..\tests\TestUtilities\Please.TestUtilities\Please.TestUtilities.csproj"/>
    <PackageReference Include="Shouldly"/>
  </ItemGroup>

</Project>
