<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Moq" Version="4.20.69" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Infrastructure\Please.Infrastructure\Please.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\src\Domain\Please.Domain\Please.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\Application\Please.Application\Please.Application.csproj" />
    <ProjectReference Include="..\..\..\tests\TestUtilities\Please.TestUtilities\Please.TestUtilities.csproj" />
    <PackageReference Include="Shouldly" Version="4.3.0"/>
  </ItemGroup>

</Project>
